apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-initdb-script
  namespace: cronohub
data:
  bot_initdb.sql:
    create table users (id serial PRIMARY KEY,handle VARCHAR ( 255 ) UNIQUE NOT NULL,commands VARCHAR ( 255 ) UNIQUE NOT NULL);
    insert into users (handle, commands) values ('michelvocks', 'test,');
    insert into users (handle, commands) values ('speza', 'test,');
    insert into users (handle, commands) values ('Skarlso', 'test,');
