apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cronohub
  name: do-storage-bot-db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: "nfs"